import LegalPageLayout, { Section } from "./LegalPageLayout";

export default function TermsOfService() {
  return (
    <LegalPageLayout
      title="Terms of Service"
      description="The rules for using Primary Arch's stats, lineup builder game, and community features."
      path="/terms-of-service"
    >
      <Section heading="What Primary Arch is">
        <p>
          Primary Arch is a statistics and entertainment site: it classifies basketball
          players into archetypes, scores and compares lineups, and offers a game (the
          "Lineup Builder") where you draft simulated rosters and play them against other
          users or simulated seasons. Nothing on this site is real-money gambling — no
          entry fees, no cash prizes, no wagering of any kind. [PLACEHOLDER: confirm this
          remains true if a monetization model changes later.]
        </p>
      </Section>

      <Section heading="Accuracy of statistics and simulations">
        <p>
          Player archetypes, scores, and simulation outcomes are generated by an algorithm
          and are provided for entertainment and analysis purposes only. They are opinions
          derived from statistical models, not facts, and should not be relied on for
          betting, professional scouting decisions, or any purpose where inaccuracy could
          cause harm. We do not guarantee the accuracy, completeness, or timeliness of any
          statistic or simulated result.
        </p>
      </Section>

      <Section heading="Accounts">
        <p>
          You're responsible for keeping your login credentials secure and for anything that
          happens under your account. You must provide an accurate email address. We may
          suspend or terminate accounts that violate these terms, abuse the game's
          matchmaking or leaderboard systems, or post content in violation of the rules
          below.
        </p>
      </Section>

      <Section heading="User-generated content">
        <p>
          Blog comments and any other content you post must not be illegal, harassing,
          hateful, or spam. We may remove content or suspend accounts that violate this at
          our discretion. You retain ownership of what you post, but grant us a license to
          display it on the site.
        </p>
      </Section>

      <Section heading="Affiliate and advertising disclosure">
        <p>
          Some pages may contain affiliate links or advertising — see the separate{" "}
          <a href="/affiliate-disclosure" style={{ color: "var(--yamabuki)" }}>Affiliate Disclosure</a> page for
          details.
        </p>
      </Section>

      <Section heading="Limitation of liability">
        <p>
          The site is provided "as is" without warranties of any kind. [PLACEHOLDER: a
          reviewer should confirm the liability-limitation and indemnification language
          appropriate for your jurisdiction — this varies significantly by country/state.]
        </p>
      </Section>

      <Section heading="Changes to these terms">
        <p>
          We may update these terms as the site evolves; continued use after an update
          means you accept the revised terms.
        </p>
      </Section>

      <Section heading="Contact">
        <p>
          Questions about these terms: [PLACEHOLDER: support email / contact page link].
        </p>
      </Section>
    </LegalPageLayout>
  );
}
